config/routes.rb
Rails.application.routes.draw do

  root to: "urls#index"

  resources :urls, only: [:create]

  resources :urls, path: "",  param: :slug, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :urls, only: [:create]
    end
  end
end

app/models/url.rb
class Url < ActiveRecord::Base
  has_many :visits

  validates :full_url, presence: true
  validates :slug, uniqueness: true
  validates :full_url, url: true

  before_save :generate_slug
  before_save :grab_title

  def generate_slug
    self.slug = SecureRandom.urlsafe_base64(4)
  end

  def grab_title
    self.title = TitleGrabber.find_title(full_url)
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :url
end

app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < ApplicationController
  respond_to :json

  def create
    respond_with(Url.create(url_params))
  end

  private

  def url_params
    params.require(:url).permit(:full_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @url = Url.new
    @urls = Url.order(created_at: :desc)
  end

  def show
    @url = Url.find_by(slug: params[:slug])
    if @url.presence
      Visit.create(url_id: @url.id)
      redirect_to @url.full_url
    else
      redirect_to root_path
    end
  end

  def create
    @url = Url.create(url_params)
    if @url.save
      flash[:notice] = "Your URL has been shrimped: http://shrimpy.me/#{@url.slug}"
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def url_params
    params.require(:url).permit(:full_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_url_table.html.erb
<div id="section-heading">
  <h3>Active Shrimpy Urls</h3>
</div>

<div id="search-form">
  <label for="searchbox"> Search by page title</label>
  <input type="text" id="searchbox">
</div>

  <table id="active-shrimps" name="active-shrimps">
    <thead>
      <tr>
        <th>Page Title</th>
        <th>Shrimped Url</th>
        <th id="visits-label">
          Visits
          <div id="sort-radio">
            <%= form_tag do %>
              <%= label_tag(:sort_popularity, "show most popular") %>
              <%= check_box_tag(:sort, "popularity") %>
            <% end %>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
    <% urls.each do |url| %>
      <tr>
        <td class="page-title"><%= url.title %></td>
        <td><%= link_to "shrimpy.me/#{url.slug}", url_path(url.slug) %></td>
        <td><%= url.visits.count %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title>Shrimpy</title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/urls/index.html.erb
<div id="main-pane">
  <div class="wrapper">
    <section>
      <h1>Shrimpy Me</h1>
      <div id="shrimpy-form">
        <%= simple_form_for @url do |f| %>

          <% if @url.errors.any? %>
            <div id="error_explanation">
              <p><%= pluralize(@url.errors.count, "error") %> prohibited this url from being shrimped:</h2>
              <ul>
              <% @url.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

        <%= f.input :full_url, label: "Enter your loooooooong URL",  placeholder: "Include http:// or https://" %>
        <%= f.submit 'Shrimpy Me' %>
      <% end %>

      </div>
      <div id="nav-arrow">
        <p>Want to see some stats?</p>
        <a id="arrow" class="fa fa-chevron-down fa-4x" href="#stats"></a>
      </div>

    </section>
  </div>
</div>
<div id="stat-pane">
  <div class="wrapper">
    <section>
      <% unless @urls.empty? %>
        <hr>
        <a name="stats"></a>

          <%= render partial: "application/url_table", locals: {:urls => @urls} %>

      <% end %>
    </section>
  </div>
</div>